[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 80
known_first_party = ["paddle", "paddle-symbolic-trace"]

[tool.ruff]
target-version = "py37"
select = [
    # Pycodestyle
    "E",
    "W",

    # Pyflakes
    "F",

    # Comprehensions
    "C4",

    # Pyupgrade
    "UP",

    # Bugbear
    "B002",
    "B003",
    "B004",
    "B009",
    "B010",
    "B011",
    "B012",
    "B013",
    "B014",
    "B015",
    "B016",
    "B017",
    "B018",
    "B019",
    "B020",
    "B021",
    "B022",
    "B025",
    "B029",
    "B032",

    # Pylint
    "PLE",
    "PLC0414",
    "PLC3002",
    "PLR0206",
    "PLR0402",
]
ignore = [
    "E402",
    "E501",
    "E722",
    "E731",
    "E741",
    "F841",
    "UP015",
    "UP038",
]

[tool.ruff.per-file-ignores]
"tests/test_dup_top.py" = ["E712"]
