name: Test

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: ./tests/
        run: |
          bash run_all.sh

      - name: Run examples
        working-directory: ./examples/
        run: |
          bash run_all.sh
